"""Tests for Claude Code parser.

This module tests the ClaudeCodeParser implementation, verifying:
- Author and body detection patterns (can_parse)
- Blocking patterns (❌ Blocking, must fix before merge)
- Approval patterns (LGTM, APPROVE, looks good, ready to merge)
- Suggestion patterns (consider, suggestion, might, recommendation)
- Correct priority and requires_investigation values
"""

import pytest

from goodtogo.core.models import CommentClassification, Priority, ReviewerType
from goodtogo.parsers.claude import ClaudeCodeParser


class TestClaudeCodeParserCanParse:
    """Tests for ClaudeCodeParser.can_parse() method."""

    @pytest.fixture
    def parser(self) -> ClaudeCodeParser:
        """Create a ClaudeCodeParser instance."""
        return ClaudeCodeParser()

    def test_can_parse_by_author_claude_bot(self, parser: ClaudeCodeParser) -> None:
        """Test detection by claude[bot] author (GitHub Actions bot)."""
        assert parser.can_parse("claude[bot]", "") is True

    def test_can_parse_by_author_claude_code_bot(self, parser: ClaudeCodeParser) -> None:
        """Test detection by claude-code[bot] author."""
        assert parser.can_parse("claude-code[bot]", "") is True

    def test_can_parse_by_author_anthropic_claude_bot(self, parser: ClaudeCodeParser) -> None:
        """Test detection by anthropic-claude[bot] author."""
        assert parser.can_parse("anthropic-claude[bot]", "") is True

    def test_can_parse_by_author_case_insensitive(self, parser: ClaudeCodeParser) -> None:
        """Test that author matching is case-insensitive."""
        assert parser.can_parse("CLAUDE[BOT]", "") is True
        assert parser.can_parse("CLAUDE-CODE[BOT]", "") is True
        assert parser.can_parse("Claude-Code[bot]", "") is True
        assert parser.can_parse("ANTHROPIC-CLAUDE[bot]", "") is True

    def test_can_parse_by_body_generated_signature(self, parser: ClaudeCodeParser) -> None:
        """Test detection by 'Generated with Claude Code' in body."""
        body = "Changes made.\n\nGenerated with Claude Code"
        assert parser.can_parse("other-user", body) is True

    def test_can_parse_by_body_claude_code_name(self, parser: ClaudeCodeParser) -> None:
        """Test detection by 'Claude Code' in body."""
        body = "This review was performed by Claude Code."
        assert parser.can_parse("other-user", body) is True

    def test_can_parse_by_body_task_completion_marker(self, parser: ClaudeCodeParser) -> None:
        """Test detection by '**Claude finished' task completion marker."""
        body = "**Claude finished @dsifry's task** —— [View job](https://...)"
        assert parser.can_parse("other-user", body) is True

    def test_can_parse_by_body_case_insensitive(self, parser: ClaudeCodeParser) -> None:
        """Test that body signature detection is case-insensitive."""
        assert parser.can_parse("other", "GENERATED WITH CLAUDE CODE") is True
        assert parser.can_parse("other", "claude code") is True
        assert parser.can_parse("other", "**CLAUDE FINISHED") is True

    def test_can_parse_non_matching_author(self, parser: ClaudeCodeParser) -> None:
        """Test that non-matching authors are rejected."""
        assert parser.can_parse("random-user", "") is False
        assert parser.can_parse("github-bot", "") is False
        assert parser.can_parse("coderabbitai[bot]", "") is False
        assert parser.can_parse("", "") is False

    def test_can_parse_non_matching_body(self, parser: ClaudeCodeParser) -> None:
        """Test that non-matching bodies are rejected."""
        assert parser.can_parse("random-user", "Regular comment body") is False
        assert parser.can_parse("random-user", "Generated by some other tool") is False


class TestClaudeCodeParserReviewerType:
    """Tests for ClaudeCodeParser.reviewer_type property."""

    def test_reviewer_type_returns_claude(self) -> None:
        """Test that reviewer_type returns CLAUDE."""
        parser = ClaudeCodeParser()
        assert parser.reviewer_type == ReviewerType.CLAUDE


class TestClaudeCodeParserBlockingPatterns:
    """Tests for blocking pattern detection (ACTIONABLE/CRITICAL)."""

    @pytest.fixture
    def parser(self) -> ClaudeCodeParser:
        """Create a ClaudeCodeParser instance."""
        return ClaudeCodeParser()

    def test_parse_blocking_emoji_marker(self, parser: ClaudeCodeParser) -> None:
        """Test '❌ Blocking' marker triggers ACTIONABLE/CRITICAL."""
        body = "❌ Blocking: This authentication bypass must be addressed."
        comment = {"body": body}
        classification, priority, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.ACTIONABLE
        assert priority == Priority.CRITICAL
        assert requires_investigation is False

    def test_parse_critical_emoji_marker(self, parser: ClaudeCodeParser) -> None:
        """Test '🔴 Critical' marker triggers ACTIONABLE/CRITICAL."""
        body = "🔴 Critical: SQL injection vulnerability detected."
        comment = {"body": body}
        classification, priority, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.ACTIONABLE
        assert priority == Priority.CRITICAL
        assert requires_investigation is False

    def test_parse_must_fix_before_merge(self, parser: ClaudeCodeParser) -> None:
        """Test 'must fix before merge' triggers ACTIONABLE/CRITICAL."""
        body = "You must fix before merge the security issue on line 42."
        comment = {"body": body}
        classification, priority, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.ACTIONABLE
        assert priority == Priority.CRITICAL
        assert requires_investigation is False

    def test_parse_required_change(self, parser: ClaudeCodeParser) -> None:
        """Test 'required change' triggers ACTIONABLE/CRITICAL."""
        body = "This is a required change for compliance."
        comment = {"body": body}
        classification, priority, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.ACTIONABLE
        assert priority == Priority.CRITICAL
        assert requires_investigation is False

    def test_parse_blocking_issue(self, parser: ClaudeCodeParser) -> None:
        """Test 'blocking issue' triggers ACTIONABLE/CRITICAL."""
        body = "This is a blocking issue that prevents deployment."
        comment = {"body": body}
        classification, priority, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.ACTIONABLE
        assert priority == Priority.CRITICAL
        assert requires_investigation is False

    def test_parse_request_changes(self, parser: ClaudeCodeParser) -> None:
        """Test 'request changes' triggers ACTIONABLE/CRITICAL."""
        body = "I request changes on this PR."
        comment = {"body": body}
        classification, priority, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.ACTIONABLE
        assert priority == Priority.CRITICAL
        assert requires_investigation is False


class TestClaudeCodeParserApprovalPatterns:
    """Tests for approval/LGTM pattern detection (NON_ACTIONABLE)."""

    @pytest.fixture
    def parser(self) -> ClaudeCodeParser:
        """Create a ClaudeCodeParser instance."""
        return ClaudeCodeParser()

    def test_parse_lgtm_keyword(self, parser: ClaudeCodeParser) -> None:
        """Test 'LGTM' keyword triggers NON_ACTIONABLE."""
        body = "LGTM!"
        comment = {"body": body}
        classification, priority, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.NON_ACTIONABLE
        assert priority == Priority.UNKNOWN
        assert requires_investigation is False

    def test_parse_lgtm_case_insensitive(self, parser: ClaudeCodeParser) -> None:
        """Test 'lgtm' is case-insensitive."""
        body = "lgtm, ship it"
        comment = {"body": body}
        classification, _, _ = parser.parse(comment)

        assert classification == CommentClassification.NON_ACTIONABLE

    def test_parse_looks_good_keyword(self, parser: ClaudeCodeParser) -> None:
        """Test 'looks good' keyword triggers NON_ACTIONABLE."""
        body = "This looks good to me."
        comment = {"body": body}
        classification, priority, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.NON_ACTIONABLE
        assert priority == Priority.UNKNOWN
        assert requires_investigation is False

    def test_parse_approve_keyword(self, parser: ClaudeCodeParser) -> None:
        """Test 'APPROVE' keyword triggers NON_ACTIONABLE."""
        body = "**Recommendation**: APPROVE"
        comment = {"body": body}
        classification, _, _ = parser.parse(comment)

        assert classification == CommentClassification.NON_ACTIONABLE

    def test_parse_ship_it_keyword(self, parser: ClaudeCodeParser) -> None:
        """Test 'ship it' keyword triggers NON_ACTIONABLE."""
        body = "Ship it!"
        comment = {"body": body}
        classification, priority, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.NON_ACTIONABLE
        assert priority == Priority.UNKNOWN
        assert requires_investigation is False

    def test_parse_ready_to_merge(self, parser: ClaudeCodeParser) -> None:
        """Test 'ready to merge' triggers NON_ACTIONABLE."""
        body = "This PR is ready to merge."
        comment = {"body": body}
        classification, _, _ = parser.parse(comment)

        assert classification == CommentClassification.NON_ACTIONABLE

    def test_parse_ready_for_production(self, parser: ClaudeCodeParser) -> None:
        """Test 'ready for production' triggers NON_ACTIONABLE."""
        body = "The code is ready for production."
        comment = {"body": body}
        classification, _, _ = parser.parse(comment)

        assert classification == CommentClassification.NON_ACTIONABLE

    def test_parse_overall_assessment_positive(self, parser: ClaudeCodeParser) -> None:
        """Test '✅ **Overall' triggers NON_ACTIONABLE."""
        body = "✅ **Overall Assessment**: Strong implementation"
        comment = {"body": body}
        classification, _, _ = parser.parse(comment)

        assert classification == CommentClassification.NON_ACTIONABLE

    def test_parse_strong_implementation(self, parser: ClaudeCodeParser) -> None:
        """Test 'strong implementation' triggers NON_ACTIONABLE."""
        body = "This is a strong implementation of the feature."
        comment = {"body": body}
        classification, _, _ = parser.parse(comment)

        assert classification == CommentClassification.NON_ACTIONABLE

    def test_parse_well_implemented(self, parser: ClaudeCodeParser) -> None:
        """Test 'well-implemented' triggers NON_ACTIONABLE."""
        body = "This is a well-implemented solution."
        comment = {"body": body}
        classification, _, _ = parser.parse(comment)

        assert classification == CommentClassification.NON_ACTIONABLE

    def test_parse_production_ready(self, parser: ClaudeCodeParser) -> None:
        """Test 'production-ready' triggers NON_ACTIONABLE."""
        body = "The code is production-ready."
        comment = {"body": body}
        classification, _, _ = parser.parse(comment)

        assert classification == CommentClassification.NON_ACTIONABLE

    def test_parse_recommend_merging(self, parser: ClaudeCodeParser) -> None:
        """Test 'recommend merging' triggers NON_ACTIONABLE."""
        body = "I recommend merging this PR."
        comment = {"body": body}
        classification, _, _ = parser.parse(comment)

        assert classification == CommentClassification.NON_ACTIONABLE


class TestClaudeCodeParserSuggestionPatterns:
    """Tests for suggestion/ambiguous pattern detection."""

    @pytest.fixture
    def parser(self) -> ClaudeCodeParser:
        """Create a ClaudeCodeParser instance."""
        return ClaudeCodeParser()

    def test_parse_consider_keyword(self, parser: ClaudeCodeParser) -> None:
        """Test 'consider' keyword triggers AMBIGUOUS."""
        body = "Consider refactoring this method."
        comment = {"body": body}
        classification, priority, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.AMBIGUOUS
        assert priority == Priority.UNKNOWN
        assert requires_investigation is True

    def test_parse_suggestion_keyword(self, parser: ClaudeCodeParser) -> None:
        """Test 'suggestion' keyword triggers AMBIGUOUS."""
        body = "Here's a suggestion: use a context manager."
        comment = {"body": body}
        classification, priority, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.AMBIGUOUS
        assert priority == Priority.UNKNOWN
        assert requires_investigation is True

    def test_parse_might_keyword(self, parser: ClaudeCodeParser) -> None:
        """Test 'might' keyword triggers AMBIGUOUS."""
        body = "You might want to add a docstring here."
        comment = {"body": body}
        classification, priority, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.AMBIGUOUS
        assert priority == Priority.UNKNOWN
        assert requires_investigation is True

    def test_parse_recommendation_keyword(self, parser: ClaudeCodeParser) -> None:
        """Test 'recommendation' keyword triggers AMBIGUOUS."""
        body = "My recommendation is to add more tests."
        comment = {"body": body}
        classification, priority, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.AMBIGUOUS
        assert priority == Priority.UNKNOWN
        assert requires_investigation is True

    def test_parse_could_be_improved(self, parser: ClaudeCodeParser) -> None:
        """Test 'could be improved' triggers AMBIGUOUS."""
        body = "The performance could be improved here."
        comment = {"body": body}
        classification, priority, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.AMBIGUOUS
        assert priority == Priority.UNKNOWN
        assert requires_investigation is True


class TestClaudeCodeParserPrecedence:
    """Tests for pattern precedence rules."""

    @pytest.fixture
    def parser(self) -> ClaudeCodeParser:
        """Create a ClaudeCodeParser instance."""
        return ClaudeCodeParser()

    def test_blocking_over_approval(self, parser: ClaudeCodeParser) -> None:
        """Test blocking patterns take precedence over approval."""
        body = "LGTM overall, but this is a blocking issue."
        comment = {"body": body}
        classification, priority, _ = parser.parse(comment)

        assert classification == CommentClassification.ACTIONABLE
        assert priority == Priority.CRITICAL

    def test_blocking_over_suggestion(self, parser: ClaudeCodeParser) -> None:
        """Test blocking patterns take precedence over suggestions."""
        body = "Consider this, but it's a required change."
        comment = {"body": body}
        classification, _, _ = parser.parse(comment)

        assert classification == CommentClassification.ACTIONABLE

    def test_approval_over_suggestion(self, parser: ClaudeCodeParser) -> None:
        """Test approval patterns take precedence over suggestions."""
        body = "LGTM! You might consider adding a test later."
        comment = {"body": body}
        classification, _, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.NON_ACTIONABLE
        assert requires_investigation is False

    def test_approval_with_general_keywords(self, parser: ClaudeCodeParser) -> None:
        """Test approval wins over general keywords like 'error' or 'bug'."""
        # This tests that a review saying "APPROVE - no bugs found" is NON_ACTIONABLE
        body = "APPROVE - No bugs or errors found in this implementation."
        comment = {"body": body}
        classification, _, _ = parser.parse(comment)

        assert classification == CommentClassification.NON_ACTIONABLE


class TestClaudeCodeParserAmbiguous:
    """Tests for default ambiguous handling."""

    @pytest.fixture
    def parser(self) -> ClaudeCodeParser:
        """Create a ClaudeCodeParser instance."""
        return ClaudeCodeParser()

    def test_parse_empty_body(self, parser: ClaudeCodeParser) -> None:
        """Test empty body results in AMBIGUOUS."""
        comment = {"body": ""}
        classification, priority, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.AMBIGUOUS
        assert priority == Priority.UNKNOWN
        assert requires_investigation is True

    def test_parse_missing_body(self, parser: ClaudeCodeParser) -> None:
        """Test missing body key results in AMBIGUOUS."""
        comment = {}
        classification, priority, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.AMBIGUOUS
        assert priority == Priority.UNKNOWN
        assert requires_investigation is True

    def test_parse_unrecognized_pattern(self, parser: ClaudeCodeParser) -> None:
        """Test unrecognized body pattern results in AMBIGUOUS."""
        comment = {"body": "The implementation is interesting."}
        classification, priority, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.AMBIGUOUS
        assert priority == Priority.UNKNOWN
        assert requires_investigation is True

    def test_parse_general_keywords_without_context(self, parser: ClaudeCodeParser) -> None:
        """Test general keywords like 'error' without blocking context are AMBIGUOUS."""
        # Simple presence of 'error' or 'bug' without explicit blocking markers
        # should be AMBIGUOUS, requiring investigation
        body = "There's an error in the validation logic."
        comment = {"body": body}
        classification, _, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.AMBIGUOUS
        assert requires_investigation is True


class TestClaudeCodeParserEdgeCases:
    """Tests for edge cases and special scenarios."""

    @pytest.fixture
    def parser(self) -> ClaudeCodeParser:
        """Create a ClaudeCodeParser instance."""
        return ClaudeCodeParser()

    def test_parse_multiple_blocking_markers(self, parser: ClaudeCodeParser) -> None:
        """Test body with multiple blocking markers."""
        body = "❌ Blocking: issue 1. Also a required change: issue 2."
        comment = {"body": body}
        classification, priority, _ = parser.parse(comment)

        assert classification == CommentClassification.ACTIONABLE
        assert priority == Priority.CRITICAL

    def test_parse_body_with_code_block_approval(self, parser: ClaudeCodeParser) -> None:
        """Test body with code block - approval pattern wins."""
        body = """
        ```python
        def must_validate():
            pass
        ```
        This looks good overall.
        """
        comment = {"body": body}
        classification, _, _ = parser.parse(comment)

        # "must_validate" in code doesn't match blocking patterns
        # "looks good" matches approval pattern -> NON_ACTIONABLE
        assert classification == CommentClassification.NON_ACTIONABLE

    def test_parse_complex_review_with_approval(self, parser: ClaudeCodeParser) -> None:
        """Test complex review with approval recommendation."""
        body = """
        **Claude finished @dsifry's task** —— [View job](https://...)

        ### Code Review Summary

        ✅ **Overall Assessment**: Strong implementation

        This is a well-implemented solution with comprehensive tests.

        **Recommendation**: APPROVE
        """
        comment = {"body": body}
        classification, _, _ = parser.parse(comment)

        assert classification == CommentClassification.NON_ACTIONABLE

    def test_parse_complex_review_with_blocking(self, parser: ClaudeCodeParser) -> None:
        """Test complex review with blocking issue."""
        body = """
        **Claude finished @dsifry's task** —— [View job](https://...)

        ### Code Review Summary

        ❌ Blocking: Security vulnerability detected.

        This implementation has a SQL injection issue that must be addressed.
        """
        comment = {"body": body}
        classification, priority, _ = parser.parse(comment)

        assert classification == CommentClassification.ACTIONABLE
        assert priority == Priority.CRITICAL


class TestClaudeCodeParserAuthorPatterns:
    """Tests for claude[bot] author pattern detection."""

    @pytest.fixture
    def parser(self) -> ClaudeCodeParser:
        """Create a ClaudeCodeParser instance."""
        return ClaudeCodeParser()

    def test_can_parse_claude_bot(self, parser: ClaudeCodeParser) -> None:
        """Test detection of claude[bot] author."""
        assert parser.can_parse("claude[bot]", "") is True

    def test_can_parse_claude_bot_case_insensitive(self, parser: ClaudeCodeParser) -> None:
        """Test claude[bot] detection is case-insensitive."""
        assert parser.can_parse("Claude[bot]", "") is True
        assert parser.can_parse("CLAUDE[BOT]", "") is True

    def test_can_parse_claude_code_bot(self, parser: ClaudeCodeParser) -> None:
        """Test detection of claude-code[bot] author."""
        assert parser.can_parse("claude-code[bot]", "") is True


class TestClaudeCodeParserSummaryPatterns:
    """Tests for Claude task completion summary pattern detection."""

    @pytest.fixture
    def parser(self) -> ClaudeCodeParser:
        """Create a ClaudeCodeParser instance."""
        return ClaudeCodeParser()

    def test_parse_task_completed_summary(self, parser: ClaudeCodeParser) -> None:
        """Test task completion summary is NON_ACTIONABLE."""
        body = "**Claude finished @dsifry's task** —— [View job](https://github.com/...)"
        comment = {"body": body}
        classification, priority, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.NON_ACTIONABLE
        assert requires_investigation is False

    def test_parse_review_summary_with_header(self, parser: ClaudeCodeParser) -> None:
        """Test review summary with ### header is NON_ACTIONABLE."""
        body = """### PR Review: GitHub Actions Documentation

#### Todo List
- [x] Read changed files
- [x] Review configuration

## Review Summary

This PR adds documentation for GitHub Actions.

## Recommendation
**Approve** - This PR is ready to merge.
"""
        comment = {"body": body}
        classification, priority, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.NON_ACTIONABLE
        assert requires_investigation is False

    def test_parse_overall_assessment_section(self, parser: ClaudeCodeParser) -> None:
        """Test comment with Overall Assessment section is NON_ACTIONABLE."""
        body = """## Review

The code looks good.

## Overall Assessment

Quality: Excellent
Security: Strong
"""
        comment = {"body": body}
        classification, priority, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.NON_ACTIONABLE
        assert requires_investigation is False

    def test_summary_takes_precedence_over_actionable_keywords(
        self, parser: ClaudeCodeParser
    ) -> None:
        """Test that summary pattern takes precedence over actionable keywords.

        Task completion summaries may contain words like 'error' or 'bug' in the
        review content, but the summary pattern should take precedence.
        """
        body = """**Claude finished @user's task** —— [View job](...)

### Review Summary

This PR fixes the bug in authentication. There was an error handling issue.

## Recommendation
**Approve**
"""
        comment = {"body": body}
        classification, priority, requires_investigation = parser.parse(comment)

        # Summary pattern should take precedence, making it NON_ACTIONABLE
        assert classification == CommentClassification.NON_ACTIONABLE
        assert requires_investigation is False

    def test_parse_task_completed_hyphenated_username(self, parser: ClaudeCodeParser) -> None:
        """Test task completion summary with hyphenated username is NON_ACTIONABLE.

        GitHub usernames can contain hyphens (e.g., 'foo-bar'), and the pattern
        must match these correctly.
        """
        body = "**Claude finished @foo-bar's task** —— [View job](https://...)"
        comment = {"body": body}
        classification, priority, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.NON_ACTIONABLE
        assert requires_investigation is False
