"""Tests for Greptile parser.

This module tests the GreptileParser implementation, verifying:
- Author and body detection patterns (can_parse)
- Actionable comment count patterns
- Review summary detection
- Correct priority and requires_investigation values
"""

import pytest

from goodtogo.core.models import CommentClassification, Priority, ReviewerType
from goodtogo.parsers.greptile import GreptileParser


class TestGreptileParserCanParse:
    """Tests for GreptileParser.can_parse() method."""

    @pytest.fixture
    def parser(self) -> GreptileParser:
        """Create a GreptileParser instance."""
        return GreptileParser()

    def test_can_parse_by_author_exact_match(self, parser: GreptileParser) -> None:
        """Test detection by exact author match."""
        assert parser.can_parse("greptile[bot]", "") is True

    def test_can_parse_by_author_case_insensitive(self, parser: GreptileParser) -> None:
        """Test that author matching is case-insensitive."""
        assert parser.can_parse("Greptile[bot]", "") is True
        assert parser.can_parse("GREPTILE[BOT]", "") is True

    def test_can_parse_by_body_greptile_link(self, parser: GreptileParser) -> None:
        """Test detection by greptile.com link in body."""
        body = "Review powered by https://greptile.com"
        assert parser.can_parse("other-user", body) is True

    def test_can_parse_by_body_greptile_name(self, parser: GreptileParser) -> None:
        """Test detection by Greptile name in body."""
        body = "This review was generated by Greptile"
        assert parser.can_parse("other-user", body) is True

    def test_can_parse_by_body_case_insensitive(self, parser: GreptileParser) -> None:
        """Test that body signature detection is case-insensitive."""
        assert parser.can_parse("other", "Check out GREPTILE.COM") is True
        assert parser.can_parse("other", "powered by greptile") is True

    def test_can_parse_non_matching_author(self, parser: GreptileParser) -> None:
        """Test that non-matching authors are rejected."""
        assert parser.can_parse("random-user", "") is False
        assert parser.can_parse("github-bot", "") is False
        assert parser.can_parse("", "") is False

    def test_can_parse_non_matching_body(self, parser: GreptileParser) -> None:
        """Test that non-matching bodies are rejected."""
        assert parser.can_parse("random-user", "Regular comment body") is False
        assert parser.can_parse("random-user", "Some other review tool") is False


class TestGreptileParserReviewerType:
    """Tests for GreptileParser.reviewer_type property."""

    def test_reviewer_type_returns_greptile(self) -> None:
        """Test that reviewer_type returns GREPTILE."""
        parser = GreptileParser()
        assert parser.reviewer_type == ReviewerType.GREPTILE


class TestGreptileParserActionableCount:
    """Tests for actionable comment count pattern detection."""

    @pytest.fixture
    def parser(self) -> GreptileParser:
        """Create a GreptileParser instance."""
        return GreptileParser()

    def test_parse_zero_actionable_comments(self, parser: GreptileParser) -> None:
        """Test zero actionable comments results in NON_ACTIONABLE."""
        body = "Actionable comments posted: 0"
        comment = {"body": body}
        classification, priority, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.NON_ACTIONABLE
        assert priority == Priority.UNKNOWN
        assert requires_investigation is False

    def test_parse_one_actionable_comment(self, parser: GreptileParser) -> None:
        """Test one actionable comment results in ACTIONABLE."""
        body = "Actionable comments posted: 1"
        comment = {"body": body}
        classification, priority, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.ACTIONABLE
        assert priority == Priority.MINOR
        assert requires_investigation is False

    def test_parse_multiple_actionable_comments(self, parser: GreptileParser) -> None:
        """Test multiple actionable comments results in ACTIONABLE."""
        body = "Actionable comments posted: 5"
        comment = {"body": body}
        classification, priority, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.ACTIONABLE
        assert priority == Priority.MINOR
        assert requires_investigation is False

    def test_parse_large_actionable_count(self, parser: GreptileParser) -> None:
        """Test large actionable comment count."""
        body = "Actionable comments posted: 100"
        comment = {"body": body}
        classification, priority, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.ACTIONABLE
        assert priority == Priority.MINOR
        assert requires_investigation is False

    def test_parse_actionable_count_case_insensitive(self, parser: GreptileParser) -> None:
        """Test actionable count pattern is case-insensitive."""
        body = "ACTIONABLE COMMENTS POSTED: 3"
        comment = {"body": body}
        classification, priority, _ = parser.parse(comment)

        assert classification == CommentClassification.ACTIONABLE

    def test_parse_actionable_count_with_whitespace(self, parser: GreptileParser) -> None:
        """Test actionable count with extra whitespace."""
        body = "Actionable comments posted:    10"
        comment = {"body": body}
        classification, priority, _ = parser.parse(comment)

        assert classification == CommentClassification.ACTIONABLE

    def test_parse_actionable_count_in_larger_body(self, parser: GreptileParser) -> None:
        """Test actionable count pattern embedded in larger body."""
        body = """
        ## Greptile Review Summary

        This PR looks good overall.

        Actionable comments posted: 2

        Please address the comments above before merging.
        """
        comment = {"body": body}
        classification, priority, _ = parser.parse(comment)

        assert classification == CommentClassification.ACTIONABLE
        assert priority == Priority.MINOR


class TestGreptileParserReviewSummary:
    """Tests for review summary detection."""

    @pytest.fixture
    def parser(self) -> GreptileParser:
        """Create a GreptileParser instance."""
        return GreptileParser()

    def test_parse_summary_header(self, parser: GreptileParser) -> None:
        """Test detection of Summary header."""
        body = "# Summary\n\nThis PR adds a new feature."
        comment = {"body": body}
        classification, priority, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.NON_ACTIONABLE
        assert priority == Priority.UNKNOWN
        assert requires_investigation is False

    def test_parse_review_summary_header(self, parser: GreptileParser) -> None:
        """Test detection of Review Summary header."""
        body = "## Review Summary\n\nNo issues found."
        comment = {"body": body}
        classification, priority, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.NON_ACTIONABLE
        assert priority == Priority.UNKNOWN
        assert requires_investigation is False

    def test_parse_pr_summary_header(self, parser: GreptileParser) -> None:
        """Test detection of PR Summary header."""
        body = "### PR Summary\n\nThis PR refactors the parser module."
        comment = {"body": body}
        classification, priority, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.NON_ACTIONABLE
        assert priority == Priority.UNKNOWN
        assert requires_investigation is False

    def test_parse_reviewed_pr_phrase(self, parser: GreptileParser) -> None:
        """Test detection of 'reviewed this PR' phrase."""
        body = "I reviewed this PR and found no issues."
        comment = {"body": body}
        classification, priority, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.NON_ACTIONABLE
        assert priority == Priority.UNKNOWN
        assert requires_investigation is False

    def test_parse_analyzed_pull_request(self, parser: GreptileParser) -> None:
        """Test detection of 'analyzed pull request' phrase."""
        body = "Greptile analyzed this pull request and found 0 issues."
        comment = {"body": body}
        classification, priority, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.NON_ACTIONABLE
        assert priority == Priority.UNKNOWN
        assert requires_investigation is False


class TestGreptileParserAmbiguous:
    """Tests for ambiguous comment handling."""

    @pytest.fixture
    def parser(self) -> GreptileParser:
        """Create a GreptileParser instance."""
        return GreptileParser()

    def test_parse_empty_body(self, parser: GreptileParser) -> None:
        """Test empty body results in AMBIGUOUS."""
        comment = {"body": ""}
        classification, priority, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.AMBIGUOUS
        assert priority == Priority.UNKNOWN
        assert requires_investigation is True

    def test_parse_missing_body(self, parser: GreptileParser) -> None:
        """Test missing body key results in AMBIGUOUS."""
        comment = {}
        classification, priority, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.AMBIGUOUS
        assert priority == Priority.UNKNOWN
        assert requires_investigation is True

    def test_parse_unrecognized_pattern(self, parser: GreptileParser) -> None:
        """Test unrecognized body pattern results in AMBIGUOUS."""
        comment = {"body": "Consider adding error handling here."}
        classification, priority, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.AMBIGUOUS
        assert priority == Priority.UNKNOWN
        assert requires_investigation is True


class TestGreptileParserEdgeCases:
    """Tests for edge cases and special scenarios."""

    @pytest.fixture
    def parser(self) -> GreptileParser:
        """Create a GreptileParser instance."""
        return GreptileParser()

    def test_actionable_count_takes_precedence_over_summary(self, parser: GreptileParser) -> None:
        """Test that actionable count takes precedence over review summary."""
        body = """
        # Summary

        This PR looks good.

        Actionable comments posted: 3
        """
        comment = {"body": body}
        classification, priority, _ = parser.parse(comment)

        # Actionable count should be found first
        assert classification == CommentClassification.ACTIONABLE
        assert priority == Priority.MINOR

    def test_zero_actionable_with_summary(self, parser: GreptileParser) -> None:
        """Test zero actionable comments with summary."""
        body = """
        # Summary

        No issues found.

        Actionable comments posted: 0
        """
        comment = {"body": body}
        classification, _, _ = parser.parse(comment)

        # Zero actionable should result in NON_ACTIONABLE
        assert classification == CommentClassification.NON_ACTIONABLE

    def test_parse_body_with_only_whitespace(self, parser: GreptileParser) -> None:
        """Test body with only whitespace results in AMBIGUOUS."""
        comment = {"body": "   \n\t\n   "}
        classification, priority, requires_investigation = parser.parse(comment)

        assert classification == CommentClassification.AMBIGUOUS
        assert requires_investigation is True
